apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-tutorialsonline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-tutorialsonline
    app.kubernetes.io/part-of: spring-boot-app-t1
  name: angular-15-client-tutoriaa8ry
spec:
  path: /
  port:
    targetPort: 4200
  to:
    kind: Service
    name: angular-15-client-tutorialsonline
    weight: null
status: {}
